server.port=8080
server.acceptqueuesize=128

jetty.servletholder.path=/issuer/igwapi/v2.0/*

db.host=localhost
db.port=3306
db.name=restjpos
db.username=root
db.password=bautista

swagger-ui.directory=/swagger-ui-dist

HOSTNAME="PCBAUTI"