user.name="bautista"

server.port=8080
server.setAcceptQueueSize=128


jetty.servletholder.path=/issuer/igwapi/v2.0/*
jetty.servletholder.initOrder=1
# FORMATO <PARAM>:<VALUE>
jetty.servletholder.initParameters  = jakarta.ws.rs.Application:org.jpos.rest.App,\
                        jersey.config.server.provider.packages:io.swagger.v3.jaxrs2.integration.resources

