user.name="bautista"

server.port=8080
server.setAcceptQueueSize=128


jetty.servletholder.path=/issuer/igwapi/v2.0/*
jetty.servletholder.initOrder=1


jetty.servletholder.initParameters[0].param=jakarta.ws.rs.Application
jetty.servletholder.initParameters[0].value = org.jpos.rest.App
jetty.servletholder.initParameters[1].param = jersey.config.server.provider.package
jetty.servletholder.initParameters[1].value = io.swagger.v3.jaxrs2.integration.resources


swagger-ui.directory=/swagger-ui-dist